baseURL = "https://sincerelylovefortech.xyz"
languageCode = "zh-cn"
title = "SLFT"
theme = "hugo-theme-stack"

[outputs]
  home = ["HTML", "RSS"]

[security]
  # 允许 html 内容
  allowContent = ['^text/html$','^text/markdown$']
  enableInlineShortcodes = true # 通常为了使用 shortcode，建议开启
